install: 
    - cinst -y pester

build: false

test_script:
    - ps: |
        $res = Invoke-Pester -PassThru
        if ($res.FailedCount -gt 0) { 
            throw "$($res.FailedCount) tests failed."
        }
